[package]
name = "isotokyo"
version = "0.0.1"
authors = ["Agiel <agiel.negura@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wgpu = "0.5"
shaderc = "0.6"
image = "0.22"
winit = { version = "0.20", features = [ "serde" ] }
cgmath = "0.17"
futures = "0.3"
bytemuck = "1.2"
serde = { version = "1.0", features = [ "derive" ] }
ron = "0.6"
